services:
  db:
    image: postgres:15-alpine
    container_name: palafeltre-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-palafeltre}
      POSTGRES_USER: ${POSTGRES_USER:-palafeltre}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-palafeltre123}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-palafeltre}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - palafeltre

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: palafeltre-backend
    environment:
      # Database
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-palafeltre}:${POSTGRES_PASSWORD:-palafeltre123}@db:5432/${POSTGRES_DB:-palafeltre}
      - STORAGE_PATH=/app/storage
      
      # Security (CHANGE IN PRODUCTION!)
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-not-for-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@palafeltre.local}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminadmin}
      - FORCE_RESET_ADMIN_PASSWORD=${FORCE_RESET_ADMIN_PASSWORD:-true}
      
      # CORS - Add your domain here
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8080,http://localhost:3000,http://127.0.0.1:8080}
      
      # OBS (optional)
      - OBS_HOST=${OBS_HOST:-localhost}
      - OBS_PORT=${OBS_PORT:-4455}
      - OBS_PASSWORD=${OBS_PASSWORD:-}
      
      # App config
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - palafeltre

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: palafeltre-frontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - palafeltre

volumes:
  db_data:
    driver: local

networks:
  palafeltre:
    driver: bridge