services:
  db:
    image: postgres:15
    container_name: palafeltre-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - palafeltre

  backend:
    image: palafeltre-backend:1.0.0 # caricato in Portainer come immagine locale
    container_name: palafeltre-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - STORAGE_PATH=/app/storage
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - storage_data:/app/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - palafeltre

  frontend:
    image: palafeltre-frontend:1.0.0 # caricato in Portainer come immagine locale
    container_name: palafeltre-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - palafeltre

volumes:
  db_data:
  storage_data:

networks:
  palafeltre:
    driver: bridge
