services:
  db:
    image: postgres:15
    container_name: palafeltre-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - palafeltre

  backend:
    # Option A (Portainer builds from Git): keep build context
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Option B (use prebuilt image): comment build above and uncomment image below
    # image: your-registry/your-namespace/palafeltre-backend:latest
    container_name: palafeltre-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - STORAGE_PATH=/app/storage
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminadmin}
      # Set to 'true' for one deploy to guarantee credentials, then set to 'false'
      - FORCE_RESET_ADMIN_PASSWORD=${FORCE_RESET_ADMIN_PASSWORD:-false}
    volumes:
      - storage_data:/app/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - palafeltre

  frontend:
    # Option A (Portainer builds from Git): keep build context
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Option B (use prebuilt image): comment build above and uncomment image below
    # image: your-registry/your-namespace/palafeltre-frontend:latest
    container_name: palafeltre-frontend
    restart: unless-stopped
    environment:
      # Prefer same-origin API calls routed via Nginx proxy at /api
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - palafeltre

volumes:
  db_data:
  storage_data:

networks:
  palafeltre:
    driver: bridge
